/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\Users\\Mrnianj\\Desktop\\Blog\\node_modules\\.store\\@vuepress+core@1.9.8\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "C:\\Users\\Mrnianj\\Desktop\\Blog\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m2 from "C:\\Users\\Mrnianj\\Desktop\\Blog\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]