/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\junnian\\Desktop\\Blog\\junnian-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-cccbafb2",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cccbafb2").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-a2ed90f2",
    path: "/basis/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a2ed90f2").then(next)
    },
  },
  {
    name: "v-57ac5574",
    path: "/amway.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57ac5574").then(next)
    },
  },
  {
    name: "v-43e8393b",
    path: "/basis/HTML.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43e8393b").then(next)
    },
  },
  {
    name: "v-b74f6692",
    path: "/basis/JavaScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b74f6692").then(next)
    },
  },
  {
    name: "v-284a5987",
    path: "/vue/vue3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-284a5987").then(next)
    },
  },
  {
    name: "v-5379884f",
    path: "/basis/DesignPatterns.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5379884f").then(next)
    },
  },
  {
    name: "v-e9742a94",
    path: "/path.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e9742a94").then(next)
    },
  },
  {
    name: "v-1a30d1e1",
    path: "/basis/ReviewJacaScript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a30d1e1").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]