/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "web Ninga",
  "description": "...",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/search.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": null,
        "heroText": "主 标题",
        "tagline": null,
        "actionText": null,
        "actionLink": "/zh/guide/",
        "footer": "MIT Licensed | Copyright © 2022-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5da2a1fe",
      "path": "/"
    },
    {
      "title": "Amway",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/amway.html",
      "relativePath": "amway.md",
      "key": "v-434e384c",
      "path": "/amway.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 字典/导航",
          "slug": "_1-字典-导航"
        },
        {
          "level": 2,
          "title": "2. Api 接口",
          "slug": "_2-api-接口"
        },
        {
          "level": 2,
          "title": "3. 社区/博客",
          "slug": "_3-社区-博客"
        },
        {
          "level": 2,
          "title": "4. JS/TS/Node",
          "slug": "_4-js-ts-node"
        },
        {
          "level": 2,
          "title": "5. 八股文",
          "slug": "_5-八股文"
        },
        {
          "level": 2,
          "title": "6. CSS",
          "slug": "_6-css"
        },
        {
          "level": 2,
          "title": "7. Git",
          "slug": "_7-git"
        },
        {
          "level": 2,
          "title": "8. web Tools",
          "slug": "_8-web-tools"
        },
        {
          "level": 2,
          "title": "9. 工程化协作",
          "slug": "_9-工程化协作"
        }
      ]
    },
    {
      "title": "设计模式",
      "frontmatter": {},
      "regularPath": "/basis/DesignPatterns.html",
      "relativePath": "basis/DesignPatterns.md",
      "key": "v-58f96035",
      "path": "/basis/DesignPatterns.html",
      "headers": [
        {
          "level": 2,
          "title": "单例模式",
          "slug": "单例模式"
        },
        {
          "level": 3,
          "title": "类实现",
          "slug": "类实现"
        },
        {
          "level": 3,
          "title": "闭包实现",
          "slug": "闭包实现"
        },
        {
          "level": 3,
          "title": "应用场景",
          "slug": "应用场景"
        },
        {
          "level": 2,
          "title": "策略模式",
          "slug": "策略模式"
        },
        {
          "level": 2,
          "title": "迭代器模式",
          "slug": "迭代器模式"
        },
        {
          "level": 2,
          "title": "观察者模式",
          "slug": "观察者模式"
        },
        {
          "level": 2,
          "title": "发布订阅模式",
          "slug": "发布订阅模式"
        },
        {
          "level": 2,
          "title": "中介者模式",
          "slug": "中介者模式"
        },
        {
          "level": 2,
          "title": "享元模式",
          "slug": "享元模式"
        }
      ]
    },
    {
      "title": "css",
      "frontmatter": {},
      "regularPath": "/basis/CSS.html",
      "relativePath": "basis/CSS.md",
      "key": "v-5be80026",
      "path": "/basis/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "CSS 学习",
          "slug": "css-学习"
        },
        {
          "level": 2,
          "title": "CSS3",
          "slug": "css3"
        },
        {
          "level": 3,
          "title": "1. 过渡效果",
          "slug": "_1-过渡效果"
        },
        {
          "level": 3,
          "title": "2. 动画",
          "slug": "_2-动画"
        },
        {
          "level": 3,
          "title": "3. 2D、3D 旋转，缩放，倾斜或平移元素",
          "slug": "_3-2d、3d-旋转-缩放-倾斜或平移元素"
        },
        {
          "level": 3,
          "title": "4. 选择器",
          "slug": "_4-选择器"
        },
        {
          "level": 3,
          "title": "5. 阴影",
          "slug": "_5-阴影"
        },
        {
          "level": 3,
          "title": "6. 边框",
          "slug": "_6-边框"
        },
        {
          "level": 3,
          "title": "7. 背景",
          "slug": "_7-背景"
        },
        {
          "level": 3,
          "title": "8. 文字",
          "slug": "_8-文字"
        },
        {
          "level": 3,
          "title": "9. 颜色和渐变",
          "slug": "_9-颜色和渐变"
        },
        {
          "level": 3,
          "title": "10.布局（重点内容）",
          "slug": "_10-布局-重点内容"
        },
        {
          "level": 3,
          "title": "11. 盒模型",
          "slug": "_11-盒模型"
        },
        {
          "level": 3,
          "title": "12.媒体查询",
          "slug": "_12-媒体查询"
        },
        {
          "level": 3,
          "title": "其它",
          "slug": "其它"
        },
        {
          "level": 2,
          "title": "Less",
          "slug": "less"
        },
        {
          "level": 2,
          "title": "Sass",
          "slug": "sass"
        },
        {
          "level": 2,
          "title": "stylus",
          "slug": "stylus"
        }
      ]
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/basis/HTML.html",
      "relativePath": "basis/HTML.md",
      "key": "v-dc4affbe",
      "path": "/basis/HTML.html",
      "headers": [
        {
          "level": 2,
          "title": "基础内容",
          "slug": "基础内容"
        },
        {
          "level": 2,
          "title": "HTML5 内容",
          "slug": "html5-内容"
        },
        {
          "level": 3,
          "title": "1. Audio、Video(多媒体支持)",
          "slug": "_1-audio、video-多媒体支持"
        },
        {
          "level": 3,
          "title": "2. Web storage",
          "slug": "_2-web-storage"
        },
        {
          "level": 3,
          "title": "3. 离线存储",
          "slug": "_3-离线存储"
        },
        {
          "level": 3,
          "title": "4. WebSocket(双向通讯长链接)",
          "slug": "_4-websocket-双向通讯长链接"
        },
        {
          "level": 3,
          "title": "5. Geolocation(地理位置 API)",
          "slug": "_5-geolocation-地理位置-api"
        },
        {
          "level": 3,
          "title": "6. Communication（跨文档消息通信）",
          "slug": "_6-communication-跨文档消息通信"
        },
        {
          "level": 3,
          "title": "7. Web Worker",
          "slug": "_7-web-worker"
        },
        {
          "level": 3,
          "title": "8. requestAnimationFrame",
          "slug": "_8-requestanimationframe"
        },
        {
          "level": 3,
          "title": "9. 摄像头",
          "slug": "_9-摄像头"
        },
        {
          "level": 3,
          "title": "10. 全屏",
          "slug": "_10-全屏"
        },
        {
          "level": 3,
          "title": "11. HTML5 拖放实现",
          "slug": "_11-html5-拖放实现"
        },
        {
          "level": 3,
          "title": "12. 其它常见的 api",
          "slug": "_12-其它常见的-api"
        },
        {
          "level": 2,
          "title": "pug",
          "slug": "pug"
        }
      ]
    },
    {
      "title": "js ninja or js killer ?",
      "frontmatter": {},
      "regularPath": "/basis/ReviewJacaScript.html",
      "relativePath": "basis/ReviewJacaScript.md",
      "key": "v-2a9646c7",
      "path": "/basis/ReviewJacaScript.html",
      "headers": [
        {
          "level": 2,
          "title": "基础内容",
          "slug": "基础内容"
        },
        {
          "level": 2,
          "title": "更多内容",
          "slug": "更多内容"
        }
      ]
    },
    {
      "title": "学习路线",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/path.html",
      "relativePath": "path.md",
      "key": "v-8f224ac8",
      "path": "/path.html",
      "headers": [
        {
          "level": 2,
          "title": "一、HTML 部分",
          "slug": "一、html-部分"
        },
        {
          "level": 2,
          "title": "二、CSS 部分",
          "slug": "二、css-部分"
        },
        {
          "level": 2,
          "title": "二、JS 部分",
          "slug": "二、js-部分"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/basis/JavaScript.html",
      "relativePath": "basis/JavaScript.md",
      "key": "v-966d2ac6",
      "path": "/basis/JavaScript.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "资源推荐",
        "link": "/amway"
      },
      {
        "text": "学习路线",
        "link": "/path"
      },
      {
        "text": "Github",
        "link": "/github"
      },
      {
        "text": "MDN",
        "link": "https://developer.mozilla.org/zh-CN/"
      }
    ]
  }
}