/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "web Ninga",
  "description": "...",
  "base": "/junnian-blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/junnian-blog/search.ico"
      }
    ],
    [
      "script",
      {},
      "\n    var _hmt = _hmt || [];\n    (function(){\n      let hm = document.createElement(\"script\");\n      hm.src = \"https://hm.baidu.com/hm.js?1a7062b879a785e4c4c743ef69d9724e\";\n      let s = document.getElementsByTagName(\"script\")[0]; \n      s.parentNode.insertBefore(hm, s);\n    })();     \n    "
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": null,
        "heroText": "主 标题",
        "tagline": null,
        "actionText": null,
        "actionLink": "/zh/guide/"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-cccbafb2",
      "path": "/",
      "lastUpdated": "2/8/2023, 1:15:30 PM",
      "lastUpdatedTimestamp": 1675833330000
    },
    {
      "title": "css",
      "frontmatter": {},
      "regularPath": "/basis/CSS.html",
      "relativePath": "basis/CSS.md",
      "key": "v-a2ed90f2",
      "path": "/basis/CSS.html",
      "headers": [
        {
          "level": 2,
          "title": "CSS 学习",
          "slug": "css-学习"
        },
        {
          "level": 2,
          "title": "CSS3",
          "slug": "css3"
        },
        {
          "level": 3,
          "title": "1. 过渡效果",
          "slug": "_1-过渡效果"
        },
        {
          "level": 3,
          "title": "2. 动画",
          "slug": "_2-动画"
        },
        {
          "level": 3,
          "title": "3. 2D、3D 旋转，缩放，倾斜或平移元素",
          "slug": "_3-2d、3d-旋转-缩放-倾斜或平移元素"
        },
        {
          "level": 3,
          "title": "4. 选择器",
          "slug": "_4-选择器"
        },
        {
          "level": 3,
          "title": "5. 阴影",
          "slug": "_5-阴影"
        },
        {
          "level": 3,
          "title": "6. 边框",
          "slug": "_6-边框"
        },
        {
          "level": 3,
          "title": "7. 背景",
          "slug": "_7-背景"
        },
        {
          "level": 3,
          "title": "8. 文字",
          "slug": "_8-文字"
        },
        {
          "level": 3,
          "title": "9. 颜色和渐变",
          "slug": "_9-颜色和渐变"
        },
        {
          "level": 3,
          "title": "10.布局（重点内容）",
          "slug": "_10-布局-重点内容"
        },
        {
          "level": 3,
          "title": "11. 盒模型",
          "slug": "_11-盒模型"
        },
        {
          "level": 3,
          "title": "12.媒体查询",
          "slug": "_12-媒体查询"
        },
        {
          "level": 3,
          "title": "其它",
          "slug": "其它"
        },
        {
          "level": 2,
          "title": "Less",
          "slug": "less"
        },
        {
          "level": 2,
          "title": "Sass",
          "slug": "sass"
        },
        {
          "level": 2,
          "title": "stylus",
          "slug": "stylus"
        }
      ],
      "lastUpdated": "2/8/2023, 3:19:32 AM",
      "lastUpdatedTimestamp": 1675797572000
    },
    {
      "title": "Amway",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/amway.html",
      "relativePath": "amway.md",
      "key": "v-57ac5574",
      "path": "/amway.html",
      "headers": [
        {
          "level": 2,
          "title": "1. 字典/导航",
          "slug": "_1-字典-导航"
        },
        {
          "level": 2,
          "title": "2. Api 接口",
          "slug": "_2-api-接口"
        },
        {
          "level": 2,
          "title": "3. 社区/博客",
          "slug": "_3-社区-博客"
        },
        {
          "level": 2,
          "title": "4. JS/TS/Node",
          "slug": "_4-js-ts-node"
        },
        {
          "level": 2,
          "title": "5. 八股文",
          "slug": "_5-八股文"
        },
        {
          "level": 2,
          "title": "6. CSS",
          "slug": "_6-css"
        },
        {
          "level": 2,
          "title": "7. Git",
          "slug": "_7-git"
        },
        {
          "level": 2,
          "title": "8. web Tools",
          "slug": "_8-web-tools"
        },
        {
          "level": 2,
          "title": "9. 工程化协作",
          "slug": "_9-工程化协作"
        }
      ],
      "lastUpdated": "2/8/2023, 3:19:32 AM",
      "lastUpdatedTimestamp": 1675797572000
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/basis/HTML.html",
      "relativePath": "basis/HTML.md",
      "key": "v-43e8393b",
      "path": "/basis/HTML.html",
      "headers": [
        {
          "level": 2,
          "title": "基础内容",
          "slug": "基础内容"
        },
        {
          "level": 2,
          "title": "HTML5 内容",
          "slug": "html5-内容"
        },
        {
          "level": 3,
          "title": "1. Audio、Video(多媒体支持)",
          "slug": "_1-audio、video-多媒体支持"
        },
        {
          "level": 3,
          "title": "2. Web storage",
          "slug": "_2-web-storage"
        },
        {
          "level": 3,
          "title": "3. 离线存储",
          "slug": "_3-离线存储"
        },
        {
          "level": 3,
          "title": "4. WebSocket(双向通讯长链接)",
          "slug": "_4-websocket-双向通讯长链接"
        },
        {
          "level": 3,
          "title": "5. Geolocation(地理位置 API)",
          "slug": "_5-geolocation-地理位置-api"
        },
        {
          "level": 3,
          "title": "6. Communication（跨文档消息通信）",
          "slug": "_6-communication-跨文档消息通信"
        },
        {
          "level": 3,
          "title": "7. Web Worker",
          "slug": "_7-web-worker"
        },
        {
          "level": 3,
          "title": "8. requestAnimationFrame",
          "slug": "_8-requestanimationframe"
        },
        {
          "level": 3,
          "title": "9. 摄像头",
          "slug": "_9-摄像头"
        },
        {
          "level": 3,
          "title": "10. 全屏",
          "slug": "_10-全屏"
        },
        {
          "level": 3,
          "title": "11. HTML5 拖放实现",
          "slug": "_11-html5-拖放实现"
        },
        {
          "level": 3,
          "title": "12. 其它常见的 api",
          "slug": "_12-其它常见的-api"
        },
        {
          "level": 2,
          "title": "pug",
          "slug": "pug"
        }
      ],
      "lastUpdated": "2/8/2023, 3:19:32 AM",
      "lastUpdatedTimestamp": 1675797572000
    },
    {
      "frontmatter": {},
      "regularPath": "/basis/JavaScript.html",
      "relativePath": "basis/JavaScript.md",
      "key": "v-b74f6692",
      "path": "/basis/JavaScript.html",
      "lastUpdated": "2/8/2023, 3:19:32 AM",
      "lastUpdatedTimestamp": 1675797572000
    },
    {
      "title": "第二十四章 EventBus",
      "frontmatter": {},
      "regularPath": "/vue/vue3.html",
      "relativePath": "vue/vue3.md",
      "key": "v-284a5987",
      "path": "/vue/vue3.html",
      "headers": [
        {
          "level": 2,
          "title": "第二十四章 EventBus",
          "slug": "第二十四章-eventbus"
        },
        {
          "level": 2,
          "title": "第二十五章 TSX",
          "slug": "第二十五章-tsx"
        },
        {
          "level": 3,
          "title": "tsx 组件形式",
          "slug": "tsx-组件形式"
        },
        {
          "level": 2,
          "title": "第二十六章 深入 v-model",
          "slug": "第二十六章-深入-v-model"
        },
        {
          "level": 2,
          "title": "第二十七章 自定义指令directive",
          "slug": "第二十七章-自定义指令directive"
        },
        {
          "level": 3,
          "title": "按钮级别鉴权示例:",
          "slug": "按钮级别鉴权示例"
        },
        {
          "level": 3,
          "title": "利用自定义指令实现拖拽效果示例：",
          "slug": "利用自定义指令实现拖拽效果示例"
        },
        {
          "level": 2,
          "title": "第二十八章 自定义Hooks",
          "slug": "第二十八章-自定义hooks"
        },
        {
          "level": 2,
          "title": "第二十九章 Vue3定义全局函数/变量",
          "slug": "第二十九章-vue3定义全局函数-变量"
        },
        {
          "level": 2,
          "title": "第三十章 Vue插件",
          "slug": "第三十章-vue插件"
        },
        {
          "level": 3,
          "title": "实现全局loading组件效果",
          "slug": "实现全局loading组件效果"
        },
        {
          "level": 2,
          "title": "第三十一章 UI 库",
          "slug": "第三十一章-ui-库"
        },
        {
          "level": 2,
          "title": "第三十二章 scoped和样式传统",
          "slug": "第三十二章-scoped和样式传统"
        },
        {
          "level": 2,
          "title": "第三十三章 css style完整新特性",
          "slug": "第三十三章-css-style完整新特性"
        },
        {
          "level": 3,
          "title": "插槽选择器",
          "slug": "插槽选择器"
        },
        {
          "level": 3,
          "title": "全局选择器（慎用）",
          "slug": "全局选择器-慎用"
        },
        {
          "level": 3,
          "title": "动态class",
          "slug": "动态class"
        },
        {
          "level": 3,
          "title": "css module",
          "slug": "css-module"
        },
        {
          "level": 3,
          "title": "css hooks",
          "slug": "css-hooks"
        },
        {
          "level": 2,
          "title": "第三十四章 Tailwind CSS",
          "slug": "第三十四章-tailwind-css"
        },
        {
          "level": 3,
          "title": "基本使用",
          "slug": "基本使用"
        },
        {
          "level": 2,
          "title": "第三十五章 Event Loop 和 nextTick",
          "slug": "第三十五章-event-loop-和-nexttick"
        }
      ],
      "lastUpdated": "2/19/2023, 10:27:18 AM",
      "lastUpdatedTimestamp": 1676773638000
    },
    {
      "title": "设计模式",
      "frontmatter": {},
      "regularPath": "/basis/DesignPatterns.html",
      "relativePath": "basis/DesignPatterns.md",
      "key": "v-5379884f",
      "path": "/basis/DesignPatterns.html",
      "headers": [
        {
          "level": 2,
          "title": "单例模式",
          "slug": "单例模式"
        },
        {
          "level": 3,
          "title": "类实现",
          "slug": "类实现"
        },
        {
          "level": 3,
          "title": "闭包实现",
          "slug": "闭包实现"
        },
        {
          "level": 3,
          "title": "应用场景",
          "slug": "应用场景"
        },
        {
          "level": 2,
          "title": "策略模式",
          "slug": "策略模式"
        },
        {
          "level": 2,
          "title": "迭代器模式",
          "slug": "迭代器模式"
        },
        {
          "level": 2,
          "title": "观察者模式",
          "slug": "观察者模式"
        },
        {
          "level": 2,
          "title": "发布订阅模式",
          "slug": "发布订阅模式"
        },
        {
          "level": 2,
          "title": "中介者模式",
          "slug": "中介者模式"
        },
        {
          "level": 2,
          "title": "享元模式",
          "slug": "享元模式"
        }
      ],
      "lastUpdated": "2/8/2023, 3:19:32 AM",
      "lastUpdatedTimestamp": 1675797572000
    },
    {
      "title": "学习路线",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/path.html",
      "relativePath": "path.md",
      "key": "v-e9742a94",
      "path": "/path.html",
      "headers": [
        {
          "level": 2,
          "title": "一、HTML 部分",
          "slug": "一、html-部分"
        },
        {
          "level": 2,
          "title": "二、CSS 部分",
          "slug": "二、css-部分"
        },
        {
          "level": 2,
          "title": "二、JS 部分",
          "slug": "二、js-部分"
        }
      ],
      "lastUpdated": "2/18/2023, 2:23:45 PM",
      "lastUpdatedTimestamp": 1676701425000
    },
    {
      "title": "js ninja or js killer ?",
      "frontmatter": {},
      "regularPath": "/basis/ReviewJacaScript.html",
      "relativePath": "basis/ReviewJacaScript.md",
      "key": "v-1a30d1e1",
      "path": "/basis/ReviewJacaScript.html",
      "headers": [
        {
          "level": 2,
          "title": "基础内容",
          "slug": "基础内容"
        },
        {
          "level": 2,
          "title": "更多内容",
          "slug": "更多内容"
        }
      ],
      "lastUpdated": "2/8/2023, 3:19:32 AM",
      "lastUpdatedTimestamp": 1675797572000
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "资源推荐",
        "link": "/amway"
      },
      {
        "text": "学习路线",
        "link": "/path"
      },
      {
        "text": "Github",
        "link": "/github"
      },
      {
        "text": "MDN",
        "link": "https://developer.mozilla.org/zh-CN/"
      }
    ],
    "lastUpdated": "最后更新日期"
  }
}